# Generated by Django 5.2.6 on 2025-10-13 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_demo', '0003_customer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer1',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='customers/'),
            preserve_default=False,
        ),
    ]
