# Generated by Django 5.2.6 on 2025-10-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_demo', '0004_customer1_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
