# Generated by Django 5.2.6 on 2025-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_demo', '0005_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cus_id',
            field=models.ManyToManyField(blank=True, to='off_demo.customer1'),
        ),
    ]
