# Generated by Django 5.2.6 on 2025-10-20 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_demo', '0006_course_cus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cus_id',
        ),
        migrations.AddField(
            model_name='course',
            name='cus_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='off_demo.customer1'),
            preserve_default=False,
        ),
    ]
