# Generated by Django 5.2.6 on 2025-11-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer2',
            name='password',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
