# Generated by Django 5.2.6 on 2025-11-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer2_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer2',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
