# Generated by Django 5.2.6 on 2025-11-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customer2_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer2',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer2',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer2',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
